// SPDX-License-Identifier: MIT
//
// Record the per-record hashes of the base conversion output.
//
// The base candidate queue is deliberately untracked (see .gitignore), so the
// tracked lock is how the repository detects that someone re-ran the conversion
// and silently changed a record that already carries a review decision. Every
// ledger entry stores the same hash, so `npm run review:verify` can name exactly
// which decisions were invalidated.
//
//   node scripts/review-lock.mjs            # write the lock
//   node scripts/review-lock.mjs --check    # fail if the base moved

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { BASE_LOCK_PATH, BASE_PATH } from "./review/build-candidate.mjs";
import { recordHash } from "./review/ledger.mjs";

const check = process.argv.includes("--check");
const base = JSON.parse(readFileSync(BASE_PATH, "utf8"));

const lock = {
  note: "sha256 of each base conversion record, in package order. Generated by scripts/review-lock.mjs.",
  basePath: BASE_PATH,
  conversionVersion: base.manifest.version,
  recordCount: base.monsters.length,
  records: Object.fromEntries(base.monsters.map(record => [record.id, recordHash(record)])),
};
const text = `${JSON.stringify(lock, null, 2)}\n`;

if (!check) {
  writeFileSync(BASE_LOCK_PATH, text, "utf8");
  console.log(`Locked ${lock.recordCount} base record(s) in ${BASE_LOCK_PATH}.`);
  process.exit(0);
}

if (!existsSync(BASE_LOCK_PATH)) {
  console.error(`${BASE_LOCK_PATH} is missing; run node scripts/review-lock.mjs.`);
  process.exit(1);
}

const stored = JSON.parse(readFileSync(BASE_LOCK_PATH, "utf8"));
const problems = [];
if (stored.recordCount !== lock.recordCount) {
  problems.push(`base record count changed: locked ${stored.recordCount}, local ${lock.recordCount}`);
}
for (const [id, hash] of Object.entries(lock.records)) {
  if (!(id in stored.records)) problems.push(`base record ${id} is new since the lock was written`);
  else if (stored.records[id] !== hash) problems.push(`base record ${id} changed since the lock was written`);
}
for (const id of Object.keys(stored.records)) {
  if (!(id in lock.records)) problems.push(`base record ${id} disappeared from the conversion output`);
}

if (problems.length > 0) {
  console.error(`Base conversion output no longer matches ${BASE_LOCK_PATH}:\n${problems.join("\n")}`);
  process.exit(1);
}
console.log(`Base conversion output matches ${BASE_LOCK_PATH} (${lock.recordCount} records).`);
