// SPDX-License-Identifier: MIT
//
// CHECKLIST.md is generated, never hand-maintained. It is a rendering of the
// same (base + repairs + decisions) inputs that produce the reviewed package, so
// the two cannot drift: `npm run review:verify` regenerates both and fails on any
// difference.

import { BATCHES } from "./queue.mjs";

const CREDIT_LINE =
  "Original GURPS conversion by Enraged Eggplant, from Monsters (May 11, 2024); adapted and republished with permission.";

export function renderChecklist({ dossiers, reviewed }) {
  const approved = dossiers.filter(entry => entry.decision?.decision === "approved");
  const rejected = dossiers.filter(entry => entry.decision?.decision === "rejected");
  const outstanding = dossiers.filter(entry => entry.decision?.decision !== "approved" && entry.decision?.decision !== "rejected");
  const batches = new Map();
  for (const entry of dossiers) {
    if (!entry.decision) continue;
    const bucket = batches.get(entry.decision.batch) ?? { approved: 0, rejected: 0, other: 0, reviewers: new Set(), dates: new Set() };
    if (entry.decision.decision === "approved") bucket.approved += 1;
    else if (entry.decision.decision === "rejected") bucket.rejected += 1;
    else bucket.other += 1;
    bucket.reviewers.add(entry.decision.reviewer);
    bucket.dates.add(entry.decision.reviewedOn);
    batches.set(entry.decision.batch, bucket);
  }

  const lines = [
    "# Enraged Eggplant SRD-Overlap Conversion Checklist",
    "",
    `<!-- Generated by scripts/review-apply.mjs from the base conversion output, review/repairs/, and`,
    `     review/decisions.jsonl. Do not edit by hand; run \`npm run review:apply\`. -->`,
    "",
    CREDIT_LINE,
    "",
    "## Plan",
    "",
    "1. Generate one authorized-public GCS v5 ancestry draft and one DOA candidate record per missing SRD-overlap monster.",
    "2. Reconcile every ancestry point total; replace reconciliation children with native GCS traits, modifiers, skills, and attacks.",
    "3. Open each `.gct` in GCS and verify attribute effects, modifiers, displayed point total, and ancestry application.",
    "4. Review each DOA Typical Stats parse, attacks, CER, threat tier, encounter frequency, treasure, size, and grappling fields.",
    "5. Change `manualReviewStatus` to `approved` only after both GCS and DOA reviews pass; then include the record in the consumable public package.",
    "",
    "## Review Progress",
    "",
    `- Candidates: ${dossiers.length}`,
    `- Approved: ${approved.length}`,
    `- Rejected: ${rejected.length}`,
    `- Outstanding: ${outstanding.length}`,
    `- Records changed by a tracked repair: ${dossiers.filter(entry => entry.applied.length > 0).length}`,
    `- Records whose ratings changed from the conversion baseline: ${dossiers.filter(entry => ratingsChanged(entry)).length}`,
    "",
    "### Batches",
    "",
    "| Batch | Approved | Rejected | Reviewers | Dates |",
    "| --- | ---: | ---: | --- | --- |",
    ...[...batches.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([name, bucket]) =>
      `| ${name} | ${bucket.approved} | ${bucket.rejected} | ${[...bucket.reviewers].sort().join(", ")} | `
      + `${[...bucket.dates].sort().join(", ")} |`),
    "",
    "### Exception Queues",
    "",
    "| Queue | Records | Outstanding |",
    "| --- | ---: | ---: |",
    ...Object.entries(BATCHES).map(([key, definition]) => {
      const matching = dossiers.filter(entry => entry.flags.includes(definition.flag));
      const open = matching.filter(entry => entry.decision?.decision !== "approved").length;
      return `| \`${key}\` — ${definition.label} | ${matching.length} | ${open} |`;
    }),
    "",
    "## Per-Monster Review",
    "",
    "| Approved | Monster | SRD | Source | Rebuilt | Cost flags | GCS | Stats | Attacks | Reconciliation | Base CER | Reviewed CER | Appearing | Wandering | Flags | Reviewer | Status |",
    "| --- | --- | --- | ---: | ---: | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | --- |",
  ];

  for (const entry of dossiers) {
    const manifest = entry.manifestEntry ?? {};
    const record = reviewed.monsters.find(monster => monster.id === entry.id);
    const status = record?.provenance.manualReviewStatus ?? "review_required";
    const flags = entry.flags.filter(flag => flag !== "ordinary");
    lines.push(
      `| ${status === "approved" ? "[x]" : "[ ]"} `
      + `| ${entry.name} `
      + `| ${(manifest.editions ?? []).join(", ")} `
      + `| ${manifest.points ?? ""} `
      + `| ${manifest.rebuilt_points ?? ""} `
      + `| ${manifest.library_cost_mismatches ?? 0} `
      + `| \`${manifest.gct ?? ""}\` `
      + `| ${manifest.stats_fields ?? ""}/12 `
      + `| ${record?.stats.attacks.length ?? 0} `
      + `| ${formatSigned(manifest.reconciliation ?? 0)} `
      + `| ${entry.baseEffectiveness.combatEffectivenessRating} `
      + `| ${entry.reviewedEffectiveness.combatEffectivenessRating} `
      + `| ${entry.reviewedEncounter.averageNumberAppearing} `
      + `| ${entry.reviewedEncounter.wanderingWeight} `
      + `| ${flags.length > 0 ? flags.join(" ") : "—"} `
      + `| ${entry.decision?.reviewer ?? "—"} `
      + `| ${status} |`,
    );
  }

  lines.push(
    "",
    "## Repairs Applied",
    "",
    "| Monster | Issue | Field | Rationale |",
    "| --- | ---: | --- | --- |",
  );
  for (const entry of dossiers) {
    for (const repair of entry.applied) {
      const fields = repair.changes.map(change => `\`${change.path}\``).join(", ") || "notes only";
      lines.push(`| ${entry.name} | #${repair.issue} | ${fields} | ${repair.rationale} |`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function ratingsChanged(entry) {
  return entry.baseEffectiveness.combatEffectivenessRating !== entry.reviewedEffectiveness.combatEffectivenessRating
    || entry.baseEffectiveness.offenseRating !== entry.reviewedEffectiveness.offenseRating
    || entry.baseEffectiveness.protectionRating !== entry.reviewedEffectiveness.protectionRating;
}

function formatSigned(value) {
  return value > 0 ? `+${value}` : String(value);
}
